/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecetasRouteImport } from './routes/_authenticated/recetas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedEntrenamientosRouteImport } from './routes/_authenticated/entrenamientos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBackendRouteImport } from './routes/_authenticated/backend'
import { Route as AuthenticatedActividadesRouteImport } from './routes/_authenticated/actividades'
import { Route as AuthenticatedCompeticionesIndexRouteImport } from './routes/_authenticated/competiciones.index'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedCompeticionesIdRouteImport } from './routes/_authenticated/competiciones.$id'
import { Route as AuthenticatedActividadesIdRouteImport } from './routes/_authenticated/actividades.$id'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecetasRoute = AuthenticatedRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrenamientosRoute =
  AuthenticatedEntrenamientosRouteImport.update({
    id: '/entrenamientos',
    path: '/entrenamientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackendRoute = AuthenticatedBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActividadesRoute =
  AuthenticatedActividadesRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompeticionesIndexRoute =
  AuthenticatedCompeticionesIndexRouteImport.update({
    id: '/competiciones/',
    path: '/competiciones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompeticionesIdRoute =
  AuthenticatedCompeticionesIdRouteImport.update({
    id: '/competiciones/$id',
    path: '/competiciones/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActividadesIdRoute =
  AuthenticatedActividadesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedActividadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/actividades': typeof AuthenticatedActividadesRouteWithChildren
  '/backend': typeof AuthenticatedBackendRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/competiciones/': typeof AuthenticatedCompeticionesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/actividades': typeof AuthenticatedActividadesRouteWithChildren
  '/backend': typeof AuthenticatedBackendRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/': typeof AuthenticatedIndexRoute
  '/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/competiciones': typeof AuthenticatedCompeticionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/_authenticated/actividades': typeof AuthenticatedActividadesRouteWithChildren
  '/_authenticated/backend': typeof AuthenticatedBackendRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/recetas': typeof AuthenticatedRecetasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/_authenticated/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/_authenticated/competiciones/': typeof AuthenticatedCompeticionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/offline'
    | '/actividades'
    | '/backend'
    | '/calendario'
    | '/entrenamientos'
    | '/perfil'
    | '/recetas'
    | '/actividades/$id'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
    | '/competiciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/offline'
    | '/actividades'
    | '/backend'
    | '/calendario'
    | '/entrenamientos'
    | '/perfil'
    | '/recetas'
    | '/'
    | '/actividades/$id'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
    | '/competiciones'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/offline'
    | '/_authenticated/actividades'
    | '/_authenticated/backend'
    | '/_authenticated/calendario'
    | '/_authenticated/entrenamientos'
    | '/_authenticated/perfil'
    | '/_authenticated/recetas'
    | '/_authenticated/'
    | '/_authenticated/actividades/$id'
    | '/_authenticated/competiciones/$id'
    | '/api/public/setup-admin'
    | '/_authenticated/competiciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfflineRoute: typeof OfflineRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recetas': {
      id: '/_authenticated/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AuthenticatedRecetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenamientos': {
      id: '/_authenticated/entrenamientos'
      path: '/entrenamientos'
      fullPath: '/entrenamientos'
      preLoaderRoute: typeof AuthenticatedEntrenamientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backend': {
      id: '/_authenticated/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof AuthenticatedBackendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividades': {
      id: '/_authenticated/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof AuthenticatedActividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competiciones/': {
      id: '/_authenticated/competiciones/'
      path: '/competiciones'
      fullPath: '/competiciones/'
      preLoaderRoute: typeof AuthenticatedCompeticionesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competiciones/$id': {
      id: '/_authenticated/competiciones/$id'
      path: '/competiciones/$id'
      fullPath: '/competiciones/$id'
      preLoaderRoute: typeof AuthenticatedCompeticionesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividades/$id': {
      id: '/_authenticated/actividades/$id'
      path: '/$id'
      fullPath: '/actividades/$id'
      preLoaderRoute: typeof AuthenticatedActividadesIdRouteImport
      parentRoute: typeof AuthenticatedActividadesRoute
    }
  }
}

interface AuthenticatedActividadesRouteChildren {
  AuthenticatedActividadesIdRoute: typeof AuthenticatedActividadesIdRoute
}

const AuthenticatedActividadesRouteChildren: AuthenticatedActividadesRouteChildren =
  {
    AuthenticatedActividadesIdRoute: AuthenticatedActividadesIdRoute,
  }

const AuthenticatedActividadesRouteWithChildren =
  AuthenticatedActividadesRoute._addFileChildren(
    AuthenticatedActividadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActividadesRoute: typeof AuthenticatedActividadesRouteWithChildren
  AuthenticatedBackendRoute: typeof AuthenticatedBackendRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEntrenamientosRoute: typeof AuthenticatedEntrenamientosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRecetasRoute: typeof AuthenticatedRecetasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompeticionesIdRoute: typeof AuthenticatedCompeticionesIdRoute
  AuthenticatedCompeticionesIndexRoute: typeof AuthenticatedCompeticionesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActividadesRoute: AuthenticatedActividadesRouteWithChildren,
  AuthenticatedBackendRoute: AuthenticatedBackendRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEntrenamientosRoute: AuthenticatedEntrenamientosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRecetasRoute: AuthenticatedRecetasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompeticionesIdRoute: AuthenticatedCompeticionesIdRoute,
  AuthenticatedCompeticionesIndexRoute: AuthenticatedCompeticionesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfflineRoute: OfflineRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
