/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecetasRouteImport } from './routes/_authenticated/recetas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedCompeticionesRouteImport } from './routes/_authenticated/competiciones'
import { Route as AuthenticatedBackendRouteImport } from './routes/_authenticated/backend'
import { Route as AuthenticatedActividadesRouteImport } from './routes/_authenticated/actividades'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedCompeticionesIdRouteImport } from './routes/_authenticated/competiciones.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecetasRoute = AuthenticatedRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompeticionesRoute =
  AuthenticatedCompeticionesRouteImport.update({
    id: '/competiciones',
    path: '/competiciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackendRoute = AuthenticatedBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActividadesRoute =
  AuthenticatedActividadesRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompeticionesIdRoute =
  AuthenticatedCompeticionesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompeticionesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/actividades': typeof AuthenticatedActividadesRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/competiciones': typeof AuthenticatedCompeticionesRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/actividades': typeof AuthenticatedActividadesRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/competiciones': typeof AuthenticatedCompeticionesRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/': typeof AuthenticatedIndexRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/actividades': typeof AuthenticatedActividadesRoute
  '/_authenticated/backend': typeof AuthenticatedBackendRoute
  '/_authenticated/competiciones': typeof AuthenticatedCompeticionesRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/recetas': typeof AuthenticatedRecetasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/actividades'
    | '/backend'
    | '/competiciones'
    | '/perfil'
    | '/recetas'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/actividades'
    | '/backend'
    | '/competiciones'
    | '/perfil'
    | '/recetas'
    | '/'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/actividades'
    | '/_authenticated/backend'
    | '/_authenticated/competiciones'
    | '/_authenticated/perfil'
    | '/_authenticated/recetas'
    | '/_authenticated/'
    | '/_authenticated/competiciones/$id'
    | '/api/public/setup-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recetas': {
      id: '/_authenticated/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AuthenticatedRecetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competiciones': {
      id: '/_authenticated/competiciones'
      path: '/competiciones'
      fullPath: '/competiciones'
      preLoaderRoute: typeof AuthenticatedCompeticionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backend': {
      id: '/_authenticated/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof AuthenticatedBackendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividades': {
      id: '/_authenticated/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof AuthenticatedActividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competiciones/$id': {
      id: '/_authenticated/competiciones/$id'
      path: '/$id'
      fullPath: '/competiciones/$id'
      preLoaderRoute: typeof AuthenticatedCompeticionesIdRouteImport
      parentRoute: typeof AuthenticatedCompeticionesRoute
    }
  }
}

interface AuthenticatedCompeticionesRouteChildren {
  AuthenticatedCompeticionesIdRoute: typeof AuthenticatedCompeticionesIdRoute
}

const AuthenticatedCompeticionesRouteChildren: AuthenticatedCompeticionesRouteChildren =
  {
    AuthenticatedCompeticionesIdRoute: AuthenticatedCompeticionesIdRoute,
  }

const AuthenticatedCompeticionesRouteWithChildren =
  AuthenticatedCompeticionesRoute._addFileChildren(
    AuthenticatedCompeticionesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActividadesRoute: typeof AuthenticatedActividadesRoute
  AuthenticatedBackendRoute: typeof AuthenticatedBackendRoute
  AuthenticatedCompeticionesRoute: typeof AuthenticatedCompeticionesRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRecetasRoute: typeof AuthenticatedRecetasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActividadesRoute: AuthenticatedActividadesRoute,
  AuthenticatedBackendRoute: AuthenticatedBackendRoute,
  AuthenticatedCompeticionesRoute: AuthenticatedCompeticionesRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRecetasRoute: AuthenticatedRecetasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
