/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReadinessRouteImport } from './routes/_authenticated/readiness'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMiBiciRouteImport } from './routes/_authenticated/mi-bici'
import { Route as AuthenticatedMenusRouteImport } from './routes/_authenticated/menus'
import { Route as AuthenticatedFtpTestRouteImport } from './routes/_authenticated/ftp-test'
import { Route as AuthenticatedEntrenamientosRouteImport } from './routes/_authenticated/entrenamientos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBackendRouteImport } from './routes/_authenticated/backend'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCompeticionesIndexRouteImport } from './routes/_authenticated/competiciones.index'
import { Route as AuthenticatedActividadesIndexRouteImport } from './routes/_authenticated/actividades.index'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedCompeticionesIdRouteImport } from './routes/_authenticated/competiciones.$id'
import { Route as AuthenticatedActividadesIdRouteImport } from './routes/_authenticated/actividades.$id'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksWeeklyWorkoutsRouteImport } from './routes/api/public/hooks/weekly-workouts'
import { Route as ApiPublicHooksReadinessPushRouteImport } from './routes/api/public/hooks/readiness-push'
import { Route as ApiPublicHooksIntervalsSyncRouteImport } from './routes/api/public/hooks/intervals-sync'
import { Route as ApiPublicHooksIntervalsDetectRouteImport } from './routes/api/public/hooks/intervals-detect'
import { Route as ApiPublicHooksActivityDetectRouteImport } from './routes/api/public/hooks/activity-detect'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReadinessRoute = AuthenticatedReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiBiciRoute = AuthenticatedMiBiciRouteImport.update({
  id: '/mi-bici',
  path: '/mi-bici',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenusRoute = AuthenticatedMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFtpTestRoute = AuthenticatedFtpTestRouteImport.update({
  id: '/ftp-test',
  path: '/ftp-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrenamientosRoute =
  AuthenticatedEntrenamientosRouteImport.update({
    id: '/entrenamientos',
    path: '/entrenamientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackendRoute = AuthenticatedBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompeticionesIndexRoute =
  AuthenticatedCompeticionesIndexRouteImport.update({
    id: '/competiciones/',
    path: '/competiciones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActividadesIndexRoute =
  AuthenticatedActividadesIndexRouteImport.update({
    id: '/actividades/',
    path: '/actividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompeticionesIdRoute =
  AuthenticatedCompeticionesIdRouteImport.update({
    id: '/competiciones/$id',
    path: '/competiciones/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActividadesIdRoute =
  AuthenticatedActividadesIdRouteImport.update({
    id: '/actividades/$id',
    path: '/actividades/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyWorkoutsRoute =
  ApiPublicHooksWeeklyWorkoutsRouteImport.update({
    id: '/api/public/hooks/weekly-workouts',
    path: '/api/public/hooks/weekly-workouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReadinessPushRoute =
  ApiPublicHooksReadinessPushRouteImport.update({
    id: '/api/public/hooks/readiness-push',
    path: '/api/public/hooks/readiness-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIntervalsSyncRoute =
  ApiPublicHooksIntervalsSyncRouteImport.update({
    id: '/api/public/hooks/intervals-sync',
    path: '/api/public/hooks/intervals-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIntervalsDetectRoute =
  ApiPublicHooksIntervalsDetectRouteImport.update({
    id: '/api/public/hooks/intervals-detect',
    path: '/api/public/hooks/intervals-detect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActivityDetectRoute =
  ApiPublicHooksActivityDetectRouteImport.update({
    id: '/api/public/hooks/activity-detect',
    path: '/api/public/hooks/activity-detect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/privacidad': typeof PrivacidadRoute
  '/app': typeof AuthenticatedAppRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/ftp-test': typeof AuthenticatedFtpTestRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/mi-bici': typeof AuthenticatedMiBiciRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/actividades/': typeof AuthenticatedActividadesIndexRoute
  '/competiciones/': typeof AuthenticatedCompeticionesIndexRoute
  '/api/public/hooks/activity-detect': typeof ApiPublicHooksActivityDetectRoute
  '/api/public/hooks/intervals-detect': typeof ApiPublicHooksIntervalsDetectRoute
  '/api/public/hooks/intervals-sync': typeof ApiPublicHooksIntervalsSyncRoute
  '/api/public/hooks/readiness-push': typeof ApiPublicHooksReadinessPushRoute
  '/api/public/hooks/weekly-workouts': typeof ApiPublicHooksWeeklyWorkoutsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/privacidad': typeof PrivacidadRoute
  '/app': typeof AuthenticatedAppRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/ftp-test': typeof AuthenticatedFtpTestRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/mi-bici': typeof AuthenticatedMiBiciRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/actividades': typeof AuthenticatedActividadesIndexRoute
  '/competiciones': typeof AuthenticatedCompeticionesIndexRoute
  '/api/public/hooks/activity-detect': typeof ApiPublicHooksActivityDetectRoute
  '/api/public/hooks/intervals-detect': typeof ApiPublicHooksIntervalsDetectRoute
  '/api/public/hooks/intervals-sync': typeof ApiPublicHooksIntervalsSyncRoute
  '/api/public/hooks/readiness-push': typeof ApiPublicHooksReadinessPushRoute
  '/api/public/hooks/weekly-workouts': typeof ApiPublicHooksWeeklyWorkoutsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/offline': typeof OfflineRoute
  '/privacidad': typeof PrivacidadRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/backend': typeof AuthenticatedBackendRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/entrenamientos': typeof AuthenticatedEntrenamientosRoute
  '/_authenticated/ftp-test': typeof AuthenticatedFtpTestRoute
  '/_authenticated/menus': typeof AuthenticatedMenusRoute
  '/_authenticated/mi-bici': typeof AuthenticatedMiBiciRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/readiness': typeof AuthenticatedReadinessRoute
  '/_authenticated/actividades/$id': typeof AuthenticatedActividadesIdRoute
  '/_authenticated/competiciones/$id': typeof AuthenticatedCompeticionesIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/_authenticated/actividades/': typeof AuthenticatedActividadesIndexRoute
  '/_authenticated/competiciones/': typeof AuthenticatedCompeticionesIndexRoute
  '/api/public/hooks/activity-detect': typeof ApiPublicHooksActivityDetectRoute
  '/api/public/hooks/intervals-detect': typeof ApiPublicHooksIntervalsDetectRoute
  '/api/public/hooks/intervals-sync': typeof ApiPublicHooksIntervalsSyncRoute
  '/api/public/hooks/readiness-push': typeof ApiPublicHooksReadinessPushRoute
  '/api/public/hooks/weekly-workouts': typeof ApiPublicHooksWeeklyWorkoutsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacidad'
    | '/app'
    | '/backend'
    | '/calendario'
    | '/entrenamientos'
    | '/ftp-test'
    | '/menus'
    | '/mi-bici'
    | '/perfil'
    | '/progreso'
    | '/readiness'
    | '/actividades/$id'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
    | '/actividades/'
    | '/competiciones/'
    | '/api/public/hooks/activity-detect'
    | '/api/public/hooks/intervals-detect'
    | '/api/public/hooks/intervals-sync'
    | '/api/public/hooks/readiness-push'
    | '/api/public/hooks/weekly-workouts'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacidad'
    | '/app'
    | '/backend'
    | '/calendario'
    | '/entrenamientos'
    | '/ftp-test'
    | '/menus'
    | '/mi-bici'
    | '/perfil'
    | '/progreso'
    | '/readiness'
    | '/actividades/$id'
    | '/competiciones/$id'
    | '/api/public/setup-admin'
    | '/actividades'
    | '/competiciones'
    | '/api/public/hooks/activity-detect'
    | '/api/public/hooks/intervals-detect'
    | '/api/public/hooks/intervals-sync'
    | '/api/public/hooks/readiness-push'
    | '/api/public/hooks/weekly-workouts'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/offline'
    | '/privacidad'
    | '/_authenticated/app'
    | '/_authenticated/backend'
    | '/_authenticated/calendario'
    | '/_authenticated/entrenamientos'
    | '/_authenticated/ftp-test'
    | '/_authenticated/menus'
    | '/_authenticated/mi-bici'
    | '/_authenticated/perfil'
    | '/_authenticated/progreso'
    | '/_authenticated/readiness'
    | '/_authenticated/actividades/$id'
    | '/_authenticated/competiciones/$id'
    | '/api/public/setup-admin'
    | '/_authenticated/actividades/'
    | '/_authenticated/competiciones/'
    | '/api/public/hooks/activity-detect'
    | '/api/public/hooks/intervals-detect'
    | '/api/public/hooks/intervals-sync'
    | '/api/public/hooks/readiness-push'
    | '/api/public/hooks/weekly-workouts'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfflineRoute: typeof OfflineRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  ApiPublicHooksActivityDetectRoute: typeof ApiPublicHooksActivityDetectRoute
  ApiPublicHooksIntervalsDetectRoute: typeof ApiPublicHooksIntervalsDetectRoute
  ApiPublicHooksIntervalsSyncRoute: typeof ApiPublicHooksIntervalsSyncRoute
  ApiPublicHooksReadinessPushRoute: typeof ApiPublicHooksReadinessPushRoute
  ApiPublicHooksWeeklyWorkoutsRoute: typeof ApiPublicHooksWeeklyWorkoutsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/readiness': {
      id: '/_authenticated/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AuthenticatedReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-bici': {
      id: '/_authenticated/mi-bici'
      path: '/mi-bici'
      fullPath: '/mi-bici'
      preLoaderRoute: typeof AuthenticatedMiBiciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menus': {
      id: '/_authenticated/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthenticatedMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ftp-test': {
      id: '/_authenticated/ftp-test'
      path: '/ftp-test'
      fullPath: '/ftp-test'
      preLoaderRoute: typeof AuthenticatedFtpTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrenamientos': {
      id: '/_authenticated/entrenamientos'
      path: '/entrenamientos'
      fullPath: '/entrenamientos'
      preLoaderRoute: typeof AuthenticatedEntrenamientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backend': {
      id: '/_authenticated/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof AuthenticatedBackendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competiciones/': {
      id: '/_authenticated/competiciones/'
      path: '/competiciones'
      fullPath: '/competiciones/'
      preLoaderRoute: typeof AuthenticatedCompeticionesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividades/': {
      id: '/_authenticated/actividades/'
      path: '/actividades'
      fullPath: '/actividades/'
      preLoaderRoute: typeof AuthenticatedActividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competiciones/$id': {
      id: '/_authenticated/competiciones/$id'
      path: '/competiciones/$id'
      fullPath: '/competiciones/$id'
      preLoaderRoute: typeof AuthenticatedCompeticionesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actividades/$id': {
      id: '/_authenticated/actividades/$id'
      path: '/actividades/$id'
      fullPath: '/actividades/$id'
      preLoaderRoute: typeof AuthenticatedActividadesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-workouts': {
      id: '/api/public/hooks/weekly-workouts'
      path: '/api/public/hooks/weekly-workouts'
      fullPath: '/api/public/hooks/weekly-workouts'
      preLoaderRoute: typeof ApiPublicHooksWeeklyWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/readiness-push': {
      id: '/api/public/hooks/readiness-push'
      path: '/api/public/hooks/readiness-push'
      fullPath: '/api/public/hooks/readiness-push'
      preLoaderRoute: typeof ApiPublicHooksReadinessPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/intervals-sync': {
      id: '/api/public/hooks/intervals-sync'
      path: '/api/public/hooks/intervals-sync'
      fullPath: '/api/public/hooks/intervals-sync'
      preLoaderRoute: typeof ApiPublicHooksIntervalsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/intervals-detect': {
      id: '/api/public/hooks/intervals-detect'
      path: '/api/public/hooks/intervals-detect'
      fullPath: '/api/public/hooks/intervals-detect'
      preLoaderRoute: typeof ApiPublicHooksIntervalsDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/activity-detect': {
      id: '/api/public/hooks/activity-detect'
      path: '/api/public/hooks/activity-detect'
      fullPath: '/api/public/hooks/activity-detect'
      preLoaderRoute: typeof ApiPublicHooksActivityDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBackendRoute: typeof AuthenticatedBackendRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEntrenamientosRoute: typeof AuthenticatedEntrenamientosRoute
  AuthenticatedFtpTestRoute: typeof AuthenticatedFtpTestRoute
  AuthenticatedMenusRoute: typeof AuthenticatedMenusRoute
  AuthenticatedMiBiciRoute: typeof AuthenticatedMiBiciRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedReadinessRoute: typeof AuthenticatedReadinessRoute
  AuthenticatedActividadesIdRoute: typeof AuthenticatedActividadesIdRoute
  AuthenticatedCompeticionesIdRoute: typeof AuthenticatedCompeticionesIdRoute
  AuthenticatedActividadesIndexRoute: typeof AuthenticatedActividadesIndexRoute
  AuthenticatedCompeticionesIndexRoute: typeof AuthenticatedCompeticionesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBackendRoute: AuthenticatedBackendRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEntrenamientosRoute: AuthenticatedEntrenamientosRoute,
  AuthenticatedFtpTestRoute: AuthenticatedFtpTestRoute,
  AuthenticatedMenusRoute: AuthenticatedMenusRoute,
  AuthenticatedMiBiciRoute: AuthenticatedMiBiciRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedReadinessRoute: AuthenticatedReadinessRoute,
  AuthenticatedActividadesIdRoute: AuthenticatedActividadesIdRoute,
  AuthenticatedCompeticionesIdRoute: AuthenticatedCompeticionesIdRoute,
  AuthenticatedActividadesIndexRoute: AuthenticatedActividadesIndexRoute,
  AuthenticatedCompeticionesIndexRoute: AuthenticatedCompeticionesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfflineRoute: OfflineRoute,
  PrivacidadRoute: PrivacidadRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  ApiPublicHooksActivityDetectRoute: ApiPublicHooksActivityDetectRoute,
  ApiPublicHooksIntervalsDetectRoute: ApiPublicHooksIntervalsDetectRoute,
  ApiPublicHooksIntervalsSyncRoute: ApiPublicHooksIntervalsSyncRoute,
  ApiPublicHooksReadinessPushRoute: ApiPublicHooksReadinessPushRoute,
  ApiPublicHooksWeeklyWorkoutsRoute: ApiPublicHooksWeeklyWorkoutsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
